### ISSUE TITLE
' in filenames makes it impossible to copy link to tools like wget axel or curl

### ISSUE THREAD

**Issue by boschkundendienst** [JupiterBroadcasting/Talks#1]
Hi Team,

using `'` in filenames makes it impossible to copy paste the link to Linux command line tools like `wget`, `axel` or `curl`. Any of the copied download links from Github will not work and you have to manually change the `' ` to `%27`. Please consider using "more compatible file names".

An example is [LFNW2019 - IronicBadger -  Home Automation with Linux that Doesn't Rely on the Cloud.mp3](https://github.com/JupiterBroadcasting/Talks/raw/master/LFNW2019/LFNW2019%20-%20IronicBadger%20-%20%20Home%20Automation%20with%20Linux%20that%20Doesn't%20Rely%20on%20the%20Cloud.mp3)

Thank you

**Comment by drewofdoom** [comment]
Two files renamed to avoid this issue.

**Comment by boschkundendienst** [comment]
**Thank you**

> Two files renamed to avoid this issue.
